apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-app-sa
  namespace: test-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-app
  name: test-app
  labels:
    app: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
      annotations:
        # Enable Vault Agent Injector
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject: "true"

        vault.hashicorp.com/role: "test_app_role"               # Vault role for the app
        vault.hashicorp.com/agent-inject-template-secret.json: |   # Template to inject secret as an env var
          {{- with secret "kv/test/test_app" -}}
          test: {{ .Data.data.test }}
          {{- end }}



    spec:
      serviceAccountName: test-app-sa # Use the service account
      containers:
      - name: test-app
        image: docker.io/sujan7410/test_app
        command: ["tail", "-f", "/dev/null"]

        ports:
        - containerPort: 3000